# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crmui2.ui'
#
# Created: Mon Mar 18 14:53:56 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CRM_form(object):
    def setupUi(self, CRM_form):
        CRM_form.setObjectName(_fromUtf8("CRM_form"))
        CRM_form.resize(718, 624)
        CRM_form.setWindowOpacity(1.0)
        self.tableWidget = QtGui.QTableWidget(CRM_form)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 681, 291))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget = QtGui.QTabWidget(CRM_form)
        self.tabWidget.setGeometry(QtCore.QRect(20, 340, 411, 261))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Look_Up = QtGui.QWidget()
        self.Look_Up.setObjectName(_fromUtf8("Look_Up"))
        self.viewallrbutt = QtGui.QPushButton(self.Look_Up)
        self.viewallrbutt.setGeometry(QtCore.QRect(10, 20, 181, 41))
        self.viewallrbutt.setObjectName(_fromUtf8("viewallrbutt"))
        self.viewallcbutt = QtGui.QPushButton(self.Look_Up)
        self.viewallcbutt.setGeometry(QtCore.QRect(220, 20, 171, 41))
        self.viewallcbutt.setObjectName(_fromUtf8("viewallcbutt"))
        self.viewallcontactsbutt = QtGui.QPushButton(self.Look_Up)
        self.viewallcontactsbutt.setGeometry(QtCore.QRect(10, 80, 181, 41))
        self.viewallcontactsbutt.setObjectName(_fromUtf8("viewallcontactsbutt"))
        self.viewallreferncebutt = QtGui.QPushButton(self.Look_Up)
        self.viewallreferncebutt.setGeometry(QtCore.QRect(220, 80, 171, 41))
        self.viewallreferncebutt.setObjectName(_fromUtf8("viewallreferncebutt"))
        self.tabWidget.addTab(self.Look_Up, _fromUtf8(""))
        self.Add = QtGui.QWidget()
        self.Add.setObjectName(_fromUtf8("Add"))
        self.time_input = QtGui.QLineEdit(self.Add)
        self.time_input.setGeometry(QtCore.QRect(130, 50, 21, 21))
        self.time_input.setObjectName(_fromUtf8("time_input"))
        self.label_2 = QtGui.QLabel(self.Add)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.dateEdit = QtGui.QDateEdit(self.Add)
        self.dateEdit.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.label_3 = QtGui.QLabel(self.Add)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 31, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.descript_cat_inut = QtGui.QComboBox(self.Add)
        self.descript_cat_inut.setGeometry(QtCore.QRect(160, 50, 111, 22))
        self.descript_cat_inut.setObjectName(_fromUtf8("descript_cat_inut"))
        self.descript_cat_inut.addItem(_fromUtf8(""))
        self.descript_cat_inut.addItem(_fromUtf8(""))
        self.descript_cat_inut.addItem(_fromUtf8(""))
        self.descript_cat_inut.addItem(_fromUtf8(""))
        self.descript_cat_inut.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.Add)
        self.label_4.setGeometry(QtCore.QRect(160, 30, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.Add)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.addsql_submitt = QtGui.QPushButton(self.Add)
        self.addsql_submitt.setGeometry(QtCore.QRect(340, 200, 51, 31))
        self.addsql_submitt.setObjectName(_fromUtf8("addsql_submitt"))
        self.label_6 = QtGui.QLabel(self.Add)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.descpt_inout = QtGui.QPlainTextEdit(self.Add)
        self.descpt_inout.setGeometry(QtCore.QRect(10, 100, 381, 91))
        self.descpt_inout.setObjectName(_fromUtf8("descpt_inout"))
        self.clientcombo = QtGui.QComboBox(self.Add)
        self.clientcombo.setGeometry(QtCore.QRect(280, 50, 111, 21))
        self.clientcombo.setObjectName(_fromUtf8("clientcombo"))
        self.clientcombo.addItem(_fromUtf8(""))
        self.clientcombo.addItem(_fromUtf8(""))
        self.clientcombo.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.Add)
        self.label_7.setGeometry(QtCore.QRect(280, 30, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.clientcontacts = QtGui.QPushButton(self.Add)
        self.clientcontacts.setGeometry(QtCore.QRect(130, 200, 91, 31))
        self.clientcontacts.setToolTip(_fromUtf8(""))
        self.clientcontacts.setObjectName(_fromUtf8("clientcontacts"))
        self.clientreffernceform = QtGui.QPushButton(self.Add)
        self.clientreffernceform.setGeometry(QtCore.QRect(10, 200, 111, 31))
        self.clientreffernceform.setToolTip(_fromUtf8(""))
        self.clientreffernceform.setObjectName(_fromUtf8("clientreffernceform"))
        self.actdelete = QtGui.QPushButton(self.Add)
        self.actdelete.setGeometry(QtCore.QRect(230, 200, 101, 31))
        self.actdelete.setObjectName(_fromUtf8("actdelete"))
        self.label_12 = QtGui.QLabel(self.Add)
        self.label_12.setGeometry(QtCore.QRect(90, 30, 31, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.unit_price = QtGui.QLineEdit(self.Add)
        self.unit_price.setGeometry(QtCore.QRect(90, 50, 31, 21))
        self.unit_price.setPlaceholderText(_fromUtf8(""))
        self.unit_price.setObjectName(_fromUtf8("unit_price"))
        self.tabWidget.addTab(self.Add, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.caddfistname = QtGui.QLineEdit(self.tab)
        self.caddfistname.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.caddfistname.setObjectName(_fromUtf8("caddfistname"))
        self.caddlastname = QtGui.QLineEdit(self.tab)
        self.caddlastname.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.caddlastname.setObjectName(_fromUtf8("caddlastname"))
        self.phonelineEdit_3 = QtGui.QLineEdit(self.tab)
        self.phonelineEdit_3.setGeometry(QtCore.QRect(20, 100, 113, 20))
        self.phonelineEdit_3.setObjectName(_fromUtf8("phonelineEdit_3"))
        self.cadddateEdit_2 = QtGui.QDateEdit(self.tab)
        self.cadddateEdit_2.setGeometry(QtCore.QRect(20, 160, 110, 22))
        self.cadddateEdit_2.setObjectName(_fromUtf8("cadddateEdit_2"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(120, 20, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 140, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.caddsumbit = QtGui.QPushButton(self.tab)
        self.caddsumbit.setGeometry(QtCore.QRect(130, 190, 81, 31))
        self.caddsumbit.setObjectName(_fromUtf8("caddsumbit"))
        self.cdelete = QtGui.QPushButton(self.tab)
        self.cdelete.setGeometry(QtCore.QRect(20, 190, 101, 31))
        self.cdelete.setObjectName(_fromUtf8("cdelete"))
        self.caddaccount = QtGui.QLineEdit(self.tab)
        self.caddaccount.setGeometry(QtCore.QRect(150, 100, 113, 20))
        self.caddaccount.setObjectName(_fromUtf8("caddaccount"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(150, 80, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.exitbutt = QtGui.QPushButton(CRM_form)
        self.exitbutt.setGeometry(QtCore.QRect(600, 570, 91, 31))
        self.exitbutt.setObjectName(_fromUtf8("exitbutt"))
        self.listWidget = QtGui.QListWidget(CRM_form)
        self.listWidget.setGeometry(QtCore.QRect(440, 360, 256, 192))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.label = QtGui.QLabel(CRM_form)
        self.label.setGeometry(QtCore.QRect(440, 330, 91, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.actionTestaction = QtGui.QAction(CRM_form)
        self.actionTestaction.setObjectName(_fromUtf8("actionTestaction"))

        self.retranslateUi(CRM_form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.viewallrbutt, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget.update)
        QtCore.QObject.connect(self.viewallcbutt, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tableWidget.selectAll)
        QtCore.QObject.connect(self.exitbutt, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.close)
        QtCore.QObject.connect(self.viewallrbutt, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.viewallcbutt, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.pyqeurry2)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), self.tableWidget.selectAll)
        QtCore.QObject.connect(self.addsql_submitt, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.pyqeurry2)
        QtCore.QObject.connect(self.dateEdit, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.descript_cat_inut, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.time_input, QtCore.SIGNAL(_fromUtf8("editingFinished()")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.descpt_inout, QtCore.SIGNAL(_fromUtf8("textChanged()")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.clientcontacts, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.clientreffernceform, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.clientcombo, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.viewallcontactsbutt, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.pyquerry1)
        QtCore.QObject.connect(self.viewallreferncebutt, QtCore.SIGNAL(_fromUtf8("clicked()")), CRM_form.pyquerry1)
        QtCore.QMetaObject.connectSlotsByName(CRM_form)

    def retranslateUi(self, CRM_form):
        CRM_form.setWindowTitle(_translate("CRM_form", "C & RM Activity Log", None))
        self.viewallrbutt.setText(_translate("CRM_form", "View All Activity Records", None))
        self.viewallcbutt.setText(_translate("CRM_form", "View All Client Records", None))
        self.viewallcontactsbutt.setText(_translate("CRM_form", "View All Contacts", None))
        self.viewallreferncebutt.setText(_translate("CRM_form", "View Reference All Forms", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Look_Up), _translate("CRM_form", "Look Up", None))
        self.time_input.setText(_translate("CRM_form", ".2", None))
        self.time_input.setPlaceholderText(_translate("CRM_form", ".2", None))
        self.label_2.setText(_translate("CRM_form", "Date:", None))
        self.label_3.setText(_translate("CRM_form", "Time:", None))
        self.descript_cat_inut.setItemText(0, _translate("CRM_form", "Care Coordination", None))
        self.descript_cat_inut.setItemText(1, _translate("CRM_form", "Correspondence", None))
        self.descript_cat_inut.setItemText(2, _translate("CRM_form", "Onsite Hospital", None))
        self.descript_cat_inut.setItemText(3, _translate("CRM_form", "Phone Call Patient", None))
        self.descript_cat_inut.setItemText(4, _translate("CRM_form", "Medical Record Review", None))
        self.label_4.setText(_translate("CRM_form", "Category:", None))
        self.label_5.setText(_translate("CRM_form", "Description of Activities:", None))
        self.addsql_submitt.setText(_translate("CRM_form", "Submit", None))
        self.label_6.setText(_translate("CRM_form", "Add Activity to the Database:", None))
        self.clientcombo.setItemText(0, _translate("CRM_form", "Luke Skywalker", None))
        self.clientcombo.setItemText(1, _translate("CRM_form", "Bill", None))
        self.clientcombo.setItemText(2, _translate("CRM_form", "Steve", None))
        self.label_7.setText(_translate("CRM_form", "Client:", None))
        self.clientcontacts.setText(_translate("CRM_form", "Client Contacts", None))
        self.clientreffernceform.setText(_translate("CRM_form", "Client Refrence Form", None))
        self.actdelete.setText(_translate("CRM_form", "Delete Last Entry", None))
        self.label_12.setText(_translate("CRM_form", "Price:", None))
        self.unit_price.setText(_translate("CRM_form", "100", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Add), _translate("CRM_form", "Add Activity", None))
        self.label_8.setText(_translate("CRM_form", "First Name:", None))
        self.label_9.setText(_translate("CRM_form", "Last Name:", None))
        self.label_10.setText(_translate("CRM_form", "Phone Number:", None))
        self.label_11.setText(_translate("CRM_form", "Date of Birth:", None))
        self.caddsumbit.setText(_translate("CRM_form", "Submit", None))
        self.cdelete.setText(_translate("CRM_form", "Delete Last Entry", None))
        self.label_13.setText(_translate("CRM_form", "Account:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CRM_form", "Add Client", None))
        self.exitbutt.setText(_translate("CRM_form", "Exit", None))
        self.label.setText(_translate("CRM_form", "Client Information", None))
        self.actionTestaction.setText(_translate("CRM_form", "Testaction", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CRM_form = QtGui.QDialog()
    ui = Ui_CRM_form()
    ui.setupUi(CRM_form)
    CRM_form.show()
    sys.exit(app.exec_())

